name       : ruby-yard
version    : 0.9.25
release    : 6
source     :
    - https://rubygems.org/downloads/yard-0.9.25.gem : 2d133b33d0bba99d10c8bca18cfbc0ab47b985ec07e79b37dd8b12b86b22d588
license    : MIT
component  : programming.ruby
summary    : YARD is a documentation generation tool for the Ruby programming language.
description: |
    YARD is a documentation generation tool for the Ruby programming language.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
