name       : ruby-yard
version    : 3.9.28
release    : 7
source     :
    - https://rubygems.org/downloads/yard-0.9.28.gem : d31b7e3172405165212e0c8db5b3b57865f0831f1bc33bdda5d0709e1e72315c
homepage   : https://rubygems.org/gems/yard
license    : MIT
component  : programming.ruby
summary    : YARD is a documentation generation tool for the Ruby programming language
description: |
    YARD is a documentation generation tool for the Ruby programming language. It enables the user to generate consistent, usable documentation that can be exported to a number of formats very easily, and also supports extending for custom Ruby constructs such as custom class level definitions.
builddeps  :
    - pkgconfig(ruby-3.1)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
